// Auto-generated by DeekeScript extension — DO NOT EDIT
// Enables VS Code JavaScript type checking for DeekeScript projects.

interface Access {
    isAccessibilityServiceEnabled(): boolean;
    isFloatWindowsEnabled(): boolean;
    isBackgroundAlertEnabled(): boolean;
    isMediaProjectionEnable(): boolean;
    openAccessibilityServiceSetting(): void;
    openFloatWindowsSetting(): void;
    openBackgroundAlertSetting(): void;
    openMediaProjectionSetting(): void;
    requestNotificationAccess(): void;
    hasNotificationAccess(): boolean;
    hasMediaReadPermission(): boolean;
    requestMediaPermissions(): void;
    openPermissionSettings(): void;
    isMediaPermissionPermanentlyDenied(): boolean;
    hasStoragePermission(): boolean;
    requestStoragePermission(): void;
    isStoragePermissionPermanentlyDenied(): boolean;
    hasLocationPermission(): boolean;
    requestLocationPermissions(): void;
    isLocationPermissionPermanentlyDenied(): boolean;
    hasBluetoothConnectionPermission(): boolean;
    requestBluetoothConnectionPermission(): void;
    isBluetoothPermissionPermanentlyDenied(): boolean;
    openBluetoothPermissionSettings(): void;
}
declare var Access: Access;

interface App {
    currentPackageName(): string;
    currentVersionCode(): number;
    currentVersionName(): string;
    packageInfo(packageName: string): any;
    gotoIntent(uri: string): void;
    startActivity(intent: Intent): void;
    backApp(): void;
    startService(service: Intent): any;
    sendBroadcast(intent: Intent): void;
    launch(packageName: string): void;
    notifySuccess(title: string, content: string): void;
    getAppVersionName(packageName: string): string;
    getAppVersionCode(packageName: string): number;
    openAppSetting(packageName: string): void;
    isAppInstalled(packageName: string): boolean;
    openUrl(url: string, packageName?: string): void;
}
declare var App: App;

interface Audio {
    load(source: string): boolean;
    play(source: string): boolean;
    play(): boolean;
    pause(): boolean;
    stop(): boolean;
    release(): void;
    seekTo(msec: number): boolean;
    setLooping(looping: boolean): boolean;
    setVolume(leftVolume: number, rightVolume: number): boolean;
    isPlaying(): boolean;
    isLoaded(): boolean;
    getDuration(): number;
    getCurrentPosition(): number;
    getCurrentSource(): string;
    canPlayInBackground(): boolean;
    hasForegroundServicePermission(): boolean;
}
declare var Audio: Audio;

interface Console {
    log(...message: any[]): void;
    warn(...message: any[]): void;
    error(...message: any[]): void;
    info(...message: any[]): void;
    debug(...message: any[]): void;
    trace(...message: any[]): void;
    show(): void;
    hide(): void;
    setWindowSize(width: number, height: number): void;
    setWindowPosition(x: number, y: number): void;
    setBackgroundColor(color: number): void;
    setTextColor(color: number): void;
    setTextSize(size: number): void;
    setLineHeight(lineHeight: number): void;
    setButtonColors(closeColor: number, resizeColor: number): void;
    setTitleTextColor(color: number): void;
    setTitleTextSize(size: number): void;
    setTitleText(text: string | null): void;
    setTitleBarColor(color: number): void;
    setAllowMoveToTop(allow: boolean): void;
    setAllowMoveToBottom(allow: boolean): void;
    setClickable(clickable: boolean): void;
    isClickable(): boolean;
    clearLogs(): void;
    setMaxLogLines(maxLines: number): void;
    getMaxLogLines(): number;
    setAutoScroll(autoScroll: boolean): void;
    setWindowStyle(config: {
        width?: number;
        height?: number;
        x?: number;
        y?: number;
        backgroundColor?: number;
        textColor?: number;
        textSize?: number;
        lineHeight?: number;
        closeButtonColor?: number;
        resizeButtonColor?: number;
        titleTextColor?: number;
        titleTextSize?: number;
        titleText?: string | null;
        titleBarColor?: number;
        allowMoveToTop?: boolean;
        allowMoveToBottom?: boolean;
        clickable?: boolean;
    }): void;
    getWindowStyle(): {
        width: number;
        height: number;
        x: number;
        y: number;
        backgroundColor: number;
        textColor: number;
        textSize: number;
        lineHeight: number;
        closeButtonColor: number;
        resizeButtonColor: number;
        titleTextColor: number;
        titleTextSize: number;
        titleText: string;
        titleBarColor: number;
        allowMoveToTop: boolean;
        allowMoveToBottom: boolean;
        clickable: boolean;
    };
    width: number;
    height: number;
    x: number;
    y: number;
    backgroundColor: number;
    textColor: number;
    textSize: number;
    lineHeight: number;
    closeButtonColor: number;
    resizeButtonColor: number;
    titleTextColor: number;
    titleTextSize: number;
    titleText: string;
    titleBarColor: number;
    allowMoveToTop: boolean;
    allowMoveToBottom: boolean;
    clickable: boolean;
}

interface DeekeBounds {
    left: number;
    top: number;
    width: number;
    height: number;
}

interface DeekeNodeInfo {
}

interface DeekeScript {
    version(): number;
    readFile(path: string): string | null;
    getProjectRoot(): string;
    getNodeFields(): string[];
    getAllAccessibilityNodeInfo(bool: boolean, fields: string[]): { nodes: DeekeNodeInfo[] } | null;
}
declare var DeekeScript: DeekeScript;

interface DeekeScriptJson {
    setDeekeScriptJsonGroup(str: string): void;
    setSettingLists(str: string): void;
    toJson(): object;
}
declare var DeekeScriptJson: DeekeScriptJson;

interface Device {
    width(): number;
    height(): number;
    pixelDensity(): number;
    sdkInt(): number;
    device(): string;
    androidVersion(): string;
    getUuid(): string;
    getToken(): string;
    getAttr(key: string): string;
    brand(): string;
    os(): string;
    model(): string;
    codename(): string;
    manufacturer(): string;
    hardware(): string;
    board(): string;
    product(): string;
    bootloader(): string;
    buildId(): string;
    display(): string;
    fingerprint(): string;
    host(): string;
    user(): string;
    getCpuAbi(): string;
    getCpuAbis(): string[];
    getWifiIPAddress(): string;
    getIPAddress(): string;
    getPublicIPAddress(): string;
    getPublicIPAddressV6(): string;
    getPublicIPInfo(): {
        ipv4: string;
        ipv6: string;
    };
    getIpInfo(): {
        ip: string;
        wifiIP: string;
        publicIP: string;
        publicIPV6: string;
        publicIPInfo: {
            ipv4: string;
            ipv6: string;
        };
    };
    getMacAddress(): string;
    getNetworkType(): "WiFi" | "Mobile" | "Ethernet" | "Other" | "None";
    isNetworkConnected(): boolean;
    getNetworkInfo(): {
        type: "WiFi" | "Mobile" | "Ethernet" | "Other" | "None";
        connected: boolean;
        macAddress: string;
        ip: string;
        wifiIP: string;
        publicIP: string;
        publicIPV6: string;
    };
    getLocation(): {
        latitude: number;
        longitude: number;
        altitude: number;
        accuracy: number;
        speed: number;
        bearing: number;
        time: number;
        provider: string;
    } | null;
    getStatusBarHeight(): number;
    getNavigationBarHeight(): number;
    getInstalledPackages(): string[];
    getInstalledApplications(): Array<{
        packageName: string;
        appName: string;
        versionName: string;
        versionCode: number;
    }>;
    ipv4: string;
    ipv6: string;
    ip: string;
    wifiIP: string;
    publicIP: string;
    publicIPV6: string;
    ipv4: string;
    ipv6: string;
    type: "WiFi" | "Mobile" | "Ethernet" | "Other" | "None";
    connected: boolean;
    macAddress: string;
    ip: string;
    wifiIP: string;
    publicIP: string;
    publicIPV6: string;
    latitude: number;
    longitude: number;
    altitude: number;
    accuracy: number;
    speed: number;
    bearing: number;
    time: number;
    provider: string;
    packageName: string;
    appName: string;
    versionName: string;
    versionCode: number;
}
declare var Device: Device;

interface DeviceApp {
    installPackage(packageUri: string): boolean;
    uninstallPackage(packageName: string): boolean;
    setApplicationHidden(packageName: string, hidden: boolean): boolean;
    isApplicationHidden(packageName: string): boolean;
    setPermissionPolicy(policy: number): boolean;
    grantRuntimePermission(packageName: string, permission: string): boolean;
    isPermissionGranted(packageName: string, permission: string): boolean;
    PERMISSION_POLICY_PROMPT: number;
    PERMISSION_POLICY_AUTO_GRANT: number;
    PERMISSION_POLICY_AUTO_DENY: number;
    PERMISSION_GRANT_STATE_DEFAULT: number;
    PERMISSION_GRANT_STATE_DENIED: number;
    PERMISSION_GRANT_STATE_GRANTED: number;
}
declare var DeviceApp: DeviceApp;

interface DeviceHardware {
    setScreenCaptureDisabled(disabled: boolean): boolean;
    setKeyguardDisabled(disabled: boolean): boolean;
    setStatusBarDisabled(disabled: boolean): boolean;
}
declare var DeviceHardware: DeviceHardware;

interface DeviceKiosk {
    setLockTaskPackages(packages: string[]): boolean;
    getLockTaskPackages(): string[] | null;
    isLockTaskModeEnabled(): boolean;
}
declare var DeviceKiosk: DeviceKiosk;

interface DevicePolicy {
    isDeviceOwner(): boolean;
    lockNow(): boolean;
    wakeScreen(): boolean;
}
declare var DevicePolicy: DevicePolicy;

interface Dialogs {
    show(title: string, content: string): void;
    show(title: string): void;
    confirm(title: string, content: string, callback: (result: boolean) => void): void;
    input(title: string): string;
    input(title: string, value: object): string;
}
declare var Dialogs: Dialogs;

interface Encrypt {
    md5(input: string): string;
    sha1(input: string): string;
    sha256(input: string): string;
    base64Encode(input: string|byte[]): string;
    base64Decode(input: string): string;
    generateIv(): string;
    aesCbcEncode(key: string, iv: string, input: string): string;
    aesCbcDecode(key: string, iv: string, input: string): string;
}
declare var Encrypt: Encrypt;

interface Engines {
    executeScript(file: string): void;
    executeScriptStr(name: string, content: string): void;
    closeAll(): void;
    closeOther(): void;
    closeHook(): void;
    childScriptCount(): number;
}
declare var Engines: Engines;

interface Files {
    read(path: string): string | null;
    write(path: string, content: string): boolean;
    append(path: string, content: string): boolean;
    delete(path: string): boolean;
    exists(path: string): boolean;
    mkdirs(path: string): boolean;
    list(path: string): string[];
    listFiles(path: string): string[];
    copy(source: string, destination: string): boolean;
    move(source: string, destination: string): boolean;
    size(path: string): number;
    isDirectory(path: string): boolean;
    isFile(path: string): boolean;
    getName(path: string): string;
    getParent(path: string): string;
    getAbsolutePath(path: string): string;
    rename(oldPath: string, newPath: string): boolean;
    lastModified(path: string): number;
    readUri(uriString: string): string | null;
    readBytesFromUri(uriString: string): number[] | null;
    getPathFromUri(uriString: string): string | null;
    readBytes(path: string): number[] | null;
    writeBytes(path: string, bytes: number[]): boolean;
    copyFromUri(uriString: string, destination: string): boolean;
    getExternalStoragePath(): string;
    getFilesPath(): string;
    getCachePath(): string;
    getExternalFilesPath(type: string | null): string;
    getExternalFilesPath(): string;
    getDownloadPath(): string;
    getPicturesPath(): string;
    getDCIMPath(): string;
    getMoviesPath(): string;
    getMusicPath(): string;
    getDocumentsPath(): string;
    readAsset(fileName: string): string | null;
    isExternalStorageWritable(): boolean;
    isExternalStorageReadable(): boolean;
    getExtension(path: string): string;
    getNameWithoutExtension(path: string): string;
}
declare var Files: Files;

interface FloatDialog {
    setContent(content: string): void;
}

interface FloatDialogs {
    show(title: string, content: string): void;
    show(content: string): void;
    toast(content: string): void;
    toastLong(content: string): void;
    setFloatWindowClickable(clickable: boolean): void;
    closeAll(): void;
    setFloatWindowVisible(visible: boolean): void;
    confirm(title: string, content: string, confirmText: string, cancelText: string, callback: (dialog: FloatDialog) => boolean | void): boolean;
}
declare var FloatDialogs: FloatDialogs;

interface ForegroundServiceBridge {
    startService(): void;
    register(func: Function): void;
    setContent(title: string, content: string): void;
    stopService(): void;
}
declare var ForegroundServiceBridge: ForegroundServiceBridge;

interface Gesture {
    click(x: number, y: number): boolean;
    longClick(x: number, y: number): boolean;
    press(x: number, y: number, duration: number): boolean;
    swipe(x1: number, y1: number, x2: number, y2: number, duration: number): boolean;
    back(): boolean;
    home(): boolean;
    recents(): boolean;
}
declare var Gesture: Gesture;

interface Hid {
    swipe(x1: number, y1: number, x2: number, y2: number, step?: number, downTimeout?: number, upTimeout?: number, timeout?: number, upDownTimes?: number): boolean;
    swipex(x1: number, y1: number, x2: number, y2: number, radian?: number, step?: number, downTimeout?: number, upTimeout?: number, timeout?: number, upDownTimes?: number): boolean;
    getHidZcm(): string;
    ver(): number;
    home(): boolean;
    recents(): boolean;
    back(): boolean;
    back1(): boolean;
    touchDown(x: number, y: number): boolean;
    touchMove(x: number, y: number): boolean;
    touchUp(x?: number, y?: number): boolean;
    touchUp2(): boolean;
    tap(x: number, y: number): boolean;
    initBluetooth(ctx: any): boolean;
    getName(): string;
    keyDown(code: number): boolean;
    keyUp(code: number): boolean;
    keyPress(code: number): boolean;
    keyPress_code(code: number): boolean;
    keyDown_code(code: number): boolean;
    keyUp_code(code: number): boolean;
    keyUpAll(): boolean;
    key_select(): boolean;
    key_paste(): boolean;
    key_copy(): boolean;
    key_cat(): boolean;
    key_del(): boolean;
    key_delete(): boolean;
    key_enter(): boolean;
    key_num(n: number): boolean;
    key_abc(n: string): boolean;
    volUp(): boolean;
    volDown(): boolean;
    power(time?: number): boolean;
    reboot(): boolean;
    setXY(x: number, y: number): boolean;
    reg(key: string): boolean;
    setRnd(x: number, y: number): boolean;
    setBattery(lv: number): boolean;
    connect(autoconnect: boolean, index: number): boolean;
    getConnectedDevices(): any;
    getConnectState(): boolean;
    sendData(str: string): boolean;
    sendDataAwait(str: string, time: number): boolean;
    getData(time?: number): string;
    waitFor(time?: number, sleep?: number): string;
    disconnect(): boolean;
}
declare var Hid: Hid;

interface Http {
    post(url: string, json: object, headers?: object): string | null;
    get(url: string, headers: object): string | null;
    postFile(url: string, files: string[], params: object, httpCallback: {
        success: (response: any) => void, fail: (response: any) => void
    }): void;
    download(url: string, destPath: string, headers?: object): string | null;
    setConnectTimeout(seconds: number): void;
    setReadTimeout(seconds: number): void;
    setWriteTimeout(seconds: number): void;
    setTimeout(connectSeconds: number, readSeconds: number, writeSeconds: number): void;
    setTimeout(seconds: number): void;
    postStream(url: string, json: object, headers: object, onData: (data: string) => void, onError: (error: string) => void): void;
    postStream(url: string, json: object, onData: (data: string) => void, onError: (error: string) => void): void;
}
declare var Http: Http;

interface Images {
    getMat(imageFile: string): Mat;
    findOne(source: Mat, template: Mat, threshold: number): Point;
    find(source: Mat, template: Mat, threshold: number): Point[];
    capture(): string;
    getColor(imageFile: string, pixelX: number, pixelY: number): string;
    findColor(imageFile: string, color: string): Point[];
    findColor(imageFile: string, startColor: string, endColor: string): Point[];
    crop(imageFile: string, left: number, top: number, width: number, height: number): string;
    scale(imageFile: string, multiple: number): string;
    getTextAndRegion(imageFile: string): TextAndRegion[];
    findTextPosition(imageFile: string, keyword: string): Rect[];
    findTextInRegion(imageFile: string, left: number, top: number, width: number, height: number): string[];
}
declare var Images: Images;

interface Intent {
    open(): void;
}
declare var Intent: Intent;

declare function JavaImporter(...packages: any[]): any;

interface KeyBoards {
    isEnabled(): boolean;
    canInput(): boolean;
    input(str: string): boolean;
    delete(): boolean;
    hide(): boolean;
    pressKey(key: string | number): boolean;
    pressEnter(): boolean;
    pressTab(): boolean;
    pressSpace(): boolean;
    showInputMethodPicker(): boolean;
}
declare var KeyBoards: KeyBoards;

interface Log {
    setFile(filename: string): boolean;
    log(...obj: object): void;
}
declare var Log: Log;

interface Mat {
}

interface MediaStore {
    getImages(): any[];
    saveImage(sourcePath: string, displayName?: string, relativePath?: string): string | null;
    saveImage(sourcePath: string): string | null;
    deleteImage(uriString: string): boolean;
    getVideos(): any[];
    saveVideo(sourcePath: string, displayName?: string, relativePath?: string): string | null;
    saveVideo(sourcePath: string): string | null;
    deleteVideo(uriString: string): boolean;
    getAudios(): any[];
    saveAudio(sourcePath: string, displayName?: string): string | null;
    saveToDownloads(sourcePath: string, displayName?: string): string | null;
    getDownloads(): any[];
    saveToDocuments(sourcePath: string, displayName?: string): string | null;
    saveToDocuments(sourcePath: string): string | null;
    getDocuments(): any[];
    readFromUri(uriString: string): number[] | null;
    queryMediaInfo(uriString: string): any;
}
declare var MediaStore: MediaStore;

interface NotificationBridge {
    startService(): void;
    startListening(onNotification: (packageName: string, title: string, text: string) => void,
        onNotificationRemoved: (packageName: string, title: string, text: string) => void): void;
    stopService(): void;
}
declare var NotificationBridge: NotificationBridge;

interface Packages {
}
declare var Packages: Packages;

interface Point {
    x: number;
    y: number;
}

declare class Rect {
    constructor(left: number, top: number, right: number, bottom: number);
    height(): number;
    width(): number;
    centerX(): number;
    centerY(): number;
    left: number;
    top: number;
    right: number;
    bottom: number;
}

interface SocketIoClient {
    getInstance(serverUrl: string, reconnect: boolean, timeout: number): socketIoClient;
    connect(): void;
    disconnect(): void;
    isConnected(): boolean;
    emit(eventName: string, data: string): void;
    emit(eventName: string, data: string, callback: function): void;
    on(eventName: string, callback: (data: string) => void): void;
    off(eventName: string, callback: (data: string) => void): void;
    off(eventName: string): void;
    off(): void;
    setReconnect(bool: boolean): void;
}
declare var SocketIoClient: SocketIoClient;

interface Storage {
    create(db: string): storage;
    put(key: string, value: string): boolean;
    putInteger(key: string, value: number): boolean;
    putBoolean(key: string, value: boolean): boolean;
    putDouble(key: string, value: number): boolean;
    putObj(key: string, obj: object): boolean;
    putArray(key: string, arr: Array): boolean;
    getArray(key: string): Array;
    get(key: string): string;
    getString(key: string): string;
    getBoolean(key: string): boolean;
    getDouble(key: string): number;
    getInteger(key: string): number;
    getObj(key: string): object;
    remove(key: string): any;
    clear(): any;
    contains(key: string): boolean;
}
declare var Storage: Storage;

interface System {
    sleep(milliSecond: number): void;
    preciseSleep(milliSecond: number): void;
    gc(): void;
    time(): string;
    currentActivity(): string;
    currentPackage(): string;
    setClip(text: string): void;
    getClip(): string;
    toast(text: string): void;
    toastLong(text: string): void;
    waitForActivity(activity: string, period: number, timeout: number): boolean;
    waitForPackage(packageName: string, period: number, timeout: number): boolean;
    exit(): void;
    cleanUp(): void;
    AiSpeechToken(key: string, secret: string): string;
    generateWindowElements(): void;
    getDataFrom(key: string, dataForm: string, content: string): string | null;
    setTimeWindowShow(show: boolean): void;
    setAccessibilityMode(mode: string): void;
    setKeepScreenOn(keepOn: boolean): void;
    getLocaleInfo(): {
        language: string;
        country: string;
        tag: string;
    };
    language: string;
    country: string;
    tag: string;
}
declare var System: System;

interface TextAndRegion {
    text: string;
    rect: Rect;
}

interface ThreadWrapper {
    start(): void;
    join(): void;
    join(millis: number): void;
    interrupt(): void;
    isAlive(): boolean;
    isInterrupted(): boolean;
    setName(name: string): void;
    getName(): string;
    setPriority(priority: number): void;
    getPriority(): number;
    getThread(): any;
}

interface Threads {
    create(runnable: (() => void) | { run: () => void }): ThreadWrapper;
    sleep(millis: number): void;
    yield(): void;
    currentThread(): ThreadWrapper;
}
declare var Threads: Threads;

interface UiObject {
    click(): boolean;
    longClick(): boolean;
    scrollForward(): boolean;
    scrollBackward(): boolean;
    setSelection(start: number, end: number): boolean;
    copy(): boolean;
    cut(): boolean;
    paste(): boolean;
    focus(): boolean;
    setText(text: string): boolean;
    find(obj: UiSelector): UiObject[];
    findOne(obj: UiSelector): UiObject;
    bounds(): Rect;
    text(): string;
    desc(): string;
    id(): string;
    children(): this;
    length(): number;
    getChildCount(): number;
    getChildren(index: any): UiObject;
    parent(): UiObject;
    getDrawingOrder(): number;
    isSelected(): boolean;
    isClickable(): boolean;
    isLongClickable(): boolean;
    isCheckable(): boolean;
    isChecked(): boolean;
    isEnabled(): boolean;
    isFocusable(): boolean;
    isFocused(): boolean;
    isScrollable(): boolean;
    isVisibleToUser(): boolean;
    isEditable(): boolean;
    isPassword(): boolean;
    className(): string;
    getPackageName(): string;
    getHintText(): string;
}

declare function UiSelector(simpleMode?: boolean): UiSelector;
interface UiSelector {
    setLevel(level: number): UiSelector;
    getLevel(): number;
    UiSelector(): void;
    UiSelector(): void;
    UiSelector(): void;
    text(text: string): UiSelector;
    textContains(text: string): UiSelector;
    textMatches(text: RegExp): UiSelector;
    textStartsWith(text: string): UiSelector;
    textEndsWith(text: string): UiSelector;
    desc(desc: string): UiSelector;
    descContains(desc: string): UiSelector;
    descMatches(desc: RegExp): UiSelector;
    descStartsWith(desc: string): UiSelector;
    descEndsWith(desc: string): UiSelector;
    className(className: string): UiSelector;
    classNameMatches(className: string): UiSelector;
    packageName(packageName: string): UiSelector;
    packageNameMatches(packageName: string): UiSelector;
    id(id: string): UiSelector;
    bounds(left: number, top: number, right: number, bottom: number): UiSelector;
    clickable(bool: boolean): UiSelector;
    checked(bool: boolean): UiSelector;
    selected(bool: boolean): UiSelector;
    enabled(bool: boolean): UiSelector;
    checked(bool: boolean): UiSelector;
    scrollable(bool: boolean): UiSelector;
    checkable(bool: boolean): UiSelector;
    focusable(bool: boolean): UiSelector;
    focused(bool: boolean): UiSelector;
    editable(bool: boolean): UiSelector;
    isVisibleToUser(bool: boolean): UiSelector;
    filter(filter: (v: UiObject) => boolean): UiSelector;
    exists(): boolean;
    waitFindOne(): UiObject;
    find(): UiObject[];
    findBy(obj: UiSelector): UiObject[];
    findBy(timeout: number): UiObject[];
    findOne(): UiObject;
    findOnce(): UiObject;
    findOneBy(obj: UiSelector): UiObject;
    findOneBy(timeout: number): UiObject;
}

interface WebSocket {
    closeAll(): void;
}
declare var WebSocket: WebSocket;

interface access {
    isAccessibilityServiceEnabled(): boolean;
    isFloatWindowsEnabled(): boolean;
    isBackgroundAlertEnabled(): boolean;
    isMediaProjectionEnable(): boolean;
    openAccessibilityServiceSetting(): void;
    openFloatWindowsSetting(): void;
    openBackgroundAlertSetting(): void;
    openMediaProjectionSetting(): void;
    requestNotificationAccess(): void;
    hasNotificationAccess(): boolean;
    hasMediaReadPermission(): boolean;
    requestMediaPermissions(): void;
    openPermissionSettings(): void;
    isMediaPermissionPermanentlyDenied(): boolean;
    hasStoragePermission(): boolean;
    requestStoragePermission(): void;
    isStoragePermissionPermanentlyDenied(): boolean;
    hasLocationPermission(): boolean;
    requestLocationPermissions(): void;
    isLocationPermissionPermanentlyDenied(): boolean;
    hasBluetoothConnectionPermission(): boolean;
    requestBluetoothConnectionPermission(): void;
    isBluetoothPermissionPermanentlyDenied(): boolean;
    openBluetoothPermissionSettings(): void;
}

interface console {
    log(...message: any[]): void;
    warn(...message: any[]): void;
    error(...message: any[]): void;
    info(...message: any[]): void;
    debug(...message: any[]): void;
    trace(...message: any[]): void;
    show(): void;
    hide(): void;
    setWindowSize(width: number, height: number): void;
    setWindowPosition(x: number, y: number): void;
    setBackgroundColor(color: number): void;
    setTextColor(color: number): void;
    setTextSize(size: number): void;
    setLineHeight(lineHeight: number): void;
    setButtonColors(closeColor: number, resizeColor: number): void;
    setTitleTextColor(color: number): void;
    setTitleTextSize(size: number): void;
    setTitleText(text: string | null): void;
    setTitleBarColor(color: number): void;
    setAllowMoveToTop(allow: boolean): void;
    setAllowMoveToBottom(allow: boolean): void;
    setClickable(clickable: boolean): void;
    isClickable(): boolean;
    clearLogs(): void;
    setMaxLogLines(maxLines: number): void;
    getMaxLogLines(): number;
    setAutoScroll(autoScroll: boolean): void;
    setWindowStyle(config: {
        width?: number;
        height?: number;
        x?: number;
        y?: number;
        backgroundColor?: number;
        textColor?: number;
        textSize?: number;
        lineHeight?: number;
        closeButtonColor?: number;
        resizeButtonColor?: number;
        titleTextColor?: number;
        titleTextSize?: number;
        titleText?: string | null;
        titleBarColor?: number;
        allowMoveToTop?: boolean;
        allowMoveToBottom?: boolean;
        clickable?: boolean;
    }): void;
    getWindowStyle(): {
        width: number;
        height: number;
        x: number;
        y: number;
        backgroundColor: number;
        textColor: number;
        textSize: number;
        lineHeight: number;
        closeButtonColor: number;
        resizeButtonColor: number;
        titleTextColor: number;
        titleTextSize: number;
        titleText: string;
        titleBarColor: number;
        allowMoveToTop: boolean;
        allowMoveToBottom: boolean;
        clickable: boolean;
    };
    width: number;
    height: number;
    x: number;
    y: number;
    backgroundColor: number;
    textColor: number;
    textSize: number;
    lineHeight: number;
    closeButtonColor: number;
    resizeButtonColor: number;
    titleTextColor: number;
    titleTextSize: number;
    titleText: string;
    titleBarColor: number;
    allowMoveToTop: boolean;
    allowMoveToBottom: boolean;
    clickable: boolean;
}
declare var console: console;

interface files {
    read(path: string): string | null;
    write(path: string, content: string): boolean;
    append(path: string, content: string): boolean;
    delete(path: string): boolean;
    exists(path: string): boolean;
    mkdirs(path: string): boolean;
    list(path: string): string[];
    listFiles(path: string): string[];
    copy(source: string, destination: string): boolean;
    move(source: string, destination: string): boolean;
    size(path: string): number;
    isDirectory(path: string): boolean;
    isFile(path: string): boolean;
    getName(path: string): string;
    getParent(path: string): string;
    getAbsolutePath(path: string): string;
    rename(oldPath: string, newPath: string): boolean;
    lastModified(path: string): number;
    readUri(uriString: string): string | null;
    readBytesFromUri(uriString: string): number[] | null;
    getPathFromUri(uriString: string): string | null;
    readBytes(path: string): number[] | null;
    writeBytes(path: string, bytes: number[]): boolean;
    copyFromUri(uriString: string, destination: string): boolean;
    getExternalStoragePath(): string;
    getFilesPath(): string;
    getCachePath(): string;
    getExternalFilesPath(type: string | null): string;
    getExternalFilesPath(): string;
    getDownloadPath(): string;
    getPicturesPath(): string;
    getDCIMPath(): string;
    getMoviesPath(): string;
    getMusicPath(): string;
    getDocumentsPath(): string;
    readAsset(fileName: string): string | null;
    isExternalStorageWritable(): boolean;
    isExternalStorageReadable(): boolean;
    getExtension(path: string): string;
    getNameWithoutExtension(path: string): string;
}

interface foregroundServiceBridge {
    startService(): void;
    register(func: Function): void;
    setContent(title: string, content: string): void;
    stopService(): void;
}

interface hid {
    swipe(x1: number, y1: number, x2: number, y2: number, step?: number, downTimeout?: number, upTimeout?: number, timeout?: number, upDownTimes?: number): boolean;
    swipex(x1: number, y1: number, x2: number, y2: number, radian?: number, step?: number, downTimeout?: number, upTimeout?: number, timeout?: number, upDownTimes?: number): boolean;
    getHidZcm(): string;
    ver(): number;
    home(): boolean;
    recents(): boolean;
    back(): boolean;
    back1(): boolean;
    touchDown(x: number, y: number): boolean;
    touchMove(x: number, y: number): boolean;
    touchUp(x?: number, y?: number): boolean;
    touchUp2(): boolean;
    tap(x: number, y: number): boolean;
    initBluetooth(ctx: any): boolean;
    getName(): string;
    keyDown(code: number): boolean;
    keyUp(code: number): boolean;
    keyPress(code: number): boolean;
    keyPress_code(code: number): boolean;
    keyDown_code(code: number): boolean;
    keyUp_code(code: number): boolean;
    keyUpAll(): boolean;
    key_select(): boolean;
    key_paste(): boolean;
    key_copy(): boolean;
    key_cat(): boolean;
    key_del(): boolean;
    key_delete(): boolean;
    key_enter(): boolean;
    key_num(n: number): boolean;
    key_abc(n: string): boolean;
    volUp(): boolean;
    volDown(): boolean;
    power(time?: number): boolean;
    reboot(): boolean;
    setXY(x: number, y: number): boolean;
    reg(key: string): boolean;
    setRnd(x: number, y: number): boolean;
    setBattery(lv: number): boolean;
    connect(autoconnect: boolean, index: number): boolean;
    getConnectedDevices(): any;
    getConnectState(): boolean;
    sendData(str: string): boolean;
    sendDataAwait(str: string, time: number): boolean;
    getData(time?: number): string;
    waitFor(time?: number, sleep?: number): string;
    disconnect(): boolean;
}

interface java {
}
declare var java: java;

interface log {
    setFile(filename: string): boolean;
    log(...obj: object): void;
}

interface notificationBridge {
    startService(): void;
    startListening(onNotification: (packageName: string, title: string, text: string) => void,
        onNotificationRemoved: (packageName: string, title: string, text: string) => void): void;
    stopService(): void;
}

interface socketIoClient {
    getInstance(serverUrl: string, reconnect: boolean, timeout: number): socketIoClient;
    connect(): void;
    disconnect(): void;
    isConnected(): boolean;
    emit(eventName: string, data: string): void;
    emit(eventName: string, data: string, callback: function): void;
    on(eventName: string, callback: (data: string) => void): void;
    off(eventName: string, callback: (data: string) => void): void;
    off(eventName: string): void;
    off(): void;
    setReconnect(bool: boolean): void;
}

interface storage {
    create(db: string): storage;
    put(key: string, value: string): boolean;
    putInteger(key: string, value: number): boolean;
    putBoolean(key: string, value: boolean): boolean;
    putDouble(key: string, value: number): boolean;
    putObj(key: string, obj: object): boolean;
    putArray(key: string, arr: Array): boolean;
    getArray(key: string): Array;
    get(key: string): string;
    getString(key: string): string;
    getBoolean(key: string): boolean;
    getDouble(key: string): number;
    getInteger(key: string): number;
    getObj(key: string): object;
    remove(key: string): any;
    clear(): any;
    contains(key: string): boolean;
}

interface webSocket {
    onOpen(): void;
    onMessage(data: string): void;
    onClose(code: number, reason: string): void;
    onError(errorMsg: string): void;
    send(data: string): void;
    close(): void;
}
